language: go

go:
  - 1.9.x
  - 1.10.x
  - "1.11"

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/gomega/...

script:
  - go test -v -covermode=count -coverprofile=profile.cov .
  - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
